export const commands = {
  mine: {
    name: "Mine",
    command: "mine",
    key: "d",
    phase: "dig",
  },
  channel: {
    name: "Channel",
    command: "channel",
    key: "h",
    phase: "dig",
  },
  upStair: {
    name: "Up Stair",
    command: "upStair",
    key: "u",
    phase: "dig",
  },
  upDownStair: {
    name: "Up/Down Stair",
    command: "upDownStair",
    key: "i",
    phase: "dig",
  },
  downStair: {
    name: "Down Stair",
    command: "downStair",
    key: "j",
    phase: "dig",
  },
  upRamp: {
    name: "Up Ramp",
    command: "upRamp",
    key: "u",
    phase: "dig",
  },
  fortification: {
    name: "Carve Fortifications",
    command: "fortification",
    key: "F",
    phase: "dig",
  },
  smooth: {
    name: "Smooth Stone",
    command: "smooth",
    key: "s",
    phase: "dig",
  },
  engrave: {
    name: "Engrave Stone",
    command: "engrave",
    key: "e",
    phase: "dig",
  },
  armorStand: {
    name: "Armor Stand",
    command: "armorStand",
    key: "a",
    phase: "build",
  },
  bed: {
    name: "Bed",
    command: "bed",
    key: "b",
    phase: "build",
  },
  seat: {
    name: "Seat",
    command: "seat",
    key: "c",
    phase: "build",
  },
  tomb: {
    name: "Burial Receptacle",
    command: "tomb",
    key: "n",
    phase: "build",
  },
  door: {
    name: "Door",
    command: "door",
    key: "d",
    phase: "build",
  },
  floodgate: {
    name: "Floodgate",
    command: "floodgate",
    key: "x",
    phase: "build",
  },
  floorHatch: {
    name: "Floor Hatch",
    command: "floorHatch",
    key: "H",
    phase: "build",
  },
  wallGrate: {
    name: "Wall Grate",
    command: "wallGrate",
    key: "W",
    phase: "build",
  },
  floorGrate: {
    name: "Floor Grate",
    command: "floorGrate",
    key: "G",
    phase: "build",
  },
  verticalBars: {
    name: "Vertical Bars",
    command: "verticalBars",
    key: "B",
    phase: "build",
  },
};
