import { CommandMap } from "./types";

export const commands: CommandMap = {
  mine: {
    name: "Mine",
    command: "mine",
    shortcut: "d",
    phase: "dig",
    type: "designation",
    textures: ["floorRough1", "floorRough2", "floorRough3", "floorRough4"],
  },
  channel: {
    name: "Channel",
    command: "channel",
    shortcut: "h",
    phase: "dig",
    type: "designation",
    textures: ["underscore"],
  },
  upStair: {
    name: "Up Stair",
    command: "upStair",
    shortcut: "u",
    phase: "dig",
    type: "designation",
    textures: ["stairsUp"],
  },
  upDownStair: {
    name: "Up/Down Stair",
    command: "upDownStair",
    shortcut: "i",
    phase: "dig",
    type: "designation",
    textures: ["X"],
  },
  downStair: {
    name: "Down Stair",
    command: "downStair",
    shortcut: "j",
    phase: "dig",
    type: "designation",
    textures: ["stairsDown"],
  },
  upRamp: {
    name: "Up Ramp",
    command: "upRamp",
    shortcut: "u",
    phase: "dig",
    type: "designation",
    textures: ["rampUp"],
  },
  fortification: {
    name: "Carve Fortifications",
    command: "fortification",
    textures: ["smoothWallCross"],
    shortcut: "F",
    phase: "designate",
    type: "designation",
  },
  smooth: {
    name: "Smooth Stone",
    command: "smooth",
    shortcut: "s",
    phase: "designate",
    type: "designation",
    textures: ["plus"],
    bitmask: true,
  },
  engrave: {
    name: "Engrave Stone",
    command: "engrave",
    shortcut: "e",
    phase: "designate",
    type: "designation",
    textures: ["smoothWallCross"],
    bitmask: true,
  },
  armorStand: {
    name: "Armor Stand",
    command: "armorStand",
    shortcut: "a",
    phase: "build",
    type: "item",
    textures: ["armorStand"],
  },
  bed: {
    name: "Bed",
    command: "bed",
    shortcut: "b",
    phase: "build",
    type: "item",
    textures: ["bed"],
    adjustments: [
      {
        type: "toggle",
        name: "Make Dining Room",
        shortcut: "r",
        initialValue: false,
      },
      {
        type: "resize",
        name: "Resize",
        decrement: "-",
        increment: "+",
        initialValue: 3,
      },
    ],
  },
  seat: {
    name: "Seat",
    command: "seat",
    shortcut: "c",
    phase: "build",
    type: "item",
    textures: ["chair"],
  },
  tomb: {
    name: "Burial Receptacle",
    command: "tomb",
    shortcut: "n",
    phase: "build",
    type: "item",
    textures: ["tomb"],
  },
  door: {
    name: "Door",
    command: "door",
    shortcut: "d",
    phase: "build",
    type: "item",
    textures: ["door"],
  },
  floodgate: {
    name: "Floodgate",
    command: "floodgate",
    shortcut: "x",
    phase: "build",
    type: "item",
    textures: ["floodgate"],
  },
  floorHatch: {
    name: "Floor Hatch",
    command: "floorHatch",
    shortcut: "H",
    phase: "build",
    type: "item",
    textures: ["hatch"],
  },
  floorGrate: {
    name: "Floor Grate",
    command: "floorGrate",
    shortcut: "G",
    phase: "build",
    type: "item",
    textures: ["grate"],
  },
  verticalBars: {
    name: "Vertical Bars",
    command: "verticalBars",
    shortcut: "B",
    phase: "build",
    type: "item",
    textures: ["bar"],
  },
  wallGrate: {
    name: "Wall Grate",
    command: "wallGrate",
    shortcut: "W",
    phase: "build",
    type: "item",
    textures: ["floodgate"],
  },
  cabinet: {
    name: "Cabinet",
    command: "cabinet",
    shortcut: "f",
    phase: "build",
    type: "item",
    textures: ["cabinet"],
  },
  container: {
    name: "Container",
    command: "container",
    shortcut: "h",
    phase: "build",
    type: "item",
    textures: ["coffer"],
  },
  kennel: {
    name: "Kennels",
    command: "kennel",
    shortcut: "k",
    phase: "build",
    type: "item",
    textures: ["earring"],
  },
  farmPlot: {
    name: "Farm Plot",
    command: "farmPlot",
    shortcut: "p",
    phase: "build",
    type: "item",
    textures: ["roadRough"],
  },
  weaponRack: {
    name: "Weapon Rack",
    command: "weaponRack",
    shortcut: "r",
    phase: "build",
    type: "item",
    textures: ["weaponRack"],
  },
  statue: {
    name: "Status",
    command: "statue",
    shortcut: "s",
    phase: "build",
    type: "item",
    textures: ["statue"],
  },
  table: {
    name: "Table",
    command: "table",
    shortcut: "t",
    phase: "build",
    type: "item",
    textures: ["table"],
    adjustments: [
      {
        type: "toggle",
        name: "Make Dining Room",
        shortcut: "r",
        initialValue: false,
      },
      {
        type: "resize",
        name: "Resize",
        decrement: "-",
        increment: "+",
        initialValue: 3,
      },
    ],
  },
  pavedRoad: {
    name: "Paved Road",
    command: "pavedRoad",
    shortcut: "o",
    phase: "build",
    type: "item",
    textures: ["plus"],
  },
  dirtRoad: {
    name: "Dirt Road",
    command: "dirtRoad",
    shortcut: "O",
    phase: "build",
    type: "item",
    textures: ["roadRough"],
  },
  bridge: {
    name: "Bridge",
    command: "bridge",
    shortcut: "g",
    phase: "build",
    type: "item",
    textures: ["plus"],
  },
  well: {
    name: "Well",
    command: "well",
    shortcut: "l",
    phase: "build",
    type: "item",
    textures: ["well"],
  },
  ballista: {
    name: "Ballista",
    command: "ballista",
    shortcut: "ib",
    phase: "build",
    type: "item",
    // this is going to be rough
    textures: ["bowyer"],
  },
  catapult: {
    name: "Catapult",
    command: "catapult",
    shortcut: "ic",
    phase: "build",
    type: "item",
    // ditto
    textures: ["bowyer"],
  },
  leatherWorks: {
    name: "Leather Works",
    command: "leatherWorks",
    shortcut: "we",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  quern: {
    name: "Quern",
    command: "quern",
    shortcut: "wq",
    phase: "build",
    type: "item",
    textures: ["W"],
  },
  millstone: {
    name: "Millstone",
    command: "millstone",
    shortcut: "wM",
    phase: "build",
    type: "item",
    textures: ["W"],
  },
  loom: {
    name: "Loom",
    command: "loom",
    shortcut: "wo",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  clothiersShop: {
    name: "Clothier's Shop",
    command: "clothiersShop",
    shortcut: "wk",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  bowyersWorkshop: {
    name: "Bowyer's Workshop",
    command: "bowyersWorkshop",
    shortcut: "wb",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  carpentersWorkshop: {
    name: "Carpenter's Workshop",
    command: "carpentersWorkshop",
    shortcut: "wc",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  metalsmithsForge: {
    name: "Metalsmith's Forge",
    command: "metalsmithsForge",
    shortcut: "wf",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  magmaForge: {
    name: "Magma Forge",
    command: "magmaForge",
    shortcut: "wv",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  jewelersWorkshop: {
    name: "Jeweler's Workshop",
    command: "jewelersWorkshop",
    shortcut: "wj",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  masonsWorkshop: {
    name: "Mason's Workshop",
    command: "masonsWorkshop",
    shortcut: "wm",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  butchersShop: {
    name: "Butcher's Shop",
    command: "butchersShop",
    shortcut: "wu",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  tannersShop: {
    name: "Tanner's Shop",
    command: "tannersShop",
    shortcut: "wn",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  craftsdwarfsWorkshop: {
    name: "Craftdwarf's Workshop",
    command: "craftsdwarfsWorkshop",
    shortcut: "wr",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  siegeWorkshop: {
    name: "Siege Workshop",
    command: "siegeWorkshop",
    shortcut: "ws",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 5,
    height: 5,
  },
  mechanicsWorkshop: {
    name: "Mechanic's Workshop",
    command: "mechanicsWorkshop",
    shortcut: "wt",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  still: {
    name: "Still",
    command: "still",
    shortcut: "wl",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  farmersWorkshop: {
    name: "Farmer's Workshop",
    command: "farmersWorkshop",
    shortcut: "ww",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  kitchen: {
    name: "Kitchen",
    command: "kitchen",
    shortcut: "wz",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  fishery: {
    name: "Fishery",
    command: "fishery",
    shortcut: "wh",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  ashery: {
    name: "ashery",
    command: "ashery",
    shortcut: "wy",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  dyersShop: {
    name: "Dyer's Shop",
    command: "dyersShop",
    shortcut: "wd",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  soapMakersWorkshop: {
    name: "Soap Maker's Workshop",
    command: "soapMakersWorkshop",
    shortcut: "wS",
    phase: "build",
    type: "item",
    textures: ["W"],
    width: 3,
    height: 3,
  },
  woodFurnace: {
    name: "Wood Furnace",
    command: "woodFurnace",
    shortcut: "ew",
    phase: "build",
    type: "item",
    textures: ["e"],
    width: 3,
    height: 3,
  },
  smelter: {
    name: "Smelter",
    command: "smelter",
    shortcut: "es",
    phase: "build",
    type: "item",
    textures: ["e"],
    width: 3,
    height: 3,
  },
  glassFurnace: {
    name: "Glass Furnace",
    command: "glassFurnace",
    shortcut: "eg",
    phase: "build",
    type: "item",
    textures: ["e"],
    width: 3,
    height: 3,
  },
  kiln: {
    name: "Kiln",
    command: "kiln",
    shortcut: "ek",
    phase: "build",
    type: "item",
    textures: ["e"],
    width: 3,
    height: 3,
  },
  magmaSmelter: {
    name: "Magma Smelter",
    command: "magmaSmelter",
    shortcut: "el",
    phase: "build",
    type: "item",
    textures: ["e"],
    width: 3,
    height: 3,
  },
  magmaGlassFurnace: {
    name: "Magma Glass Furnace",
    command: "magmaGlassFurnace",
    shortcut: "ea",
    phase: "build",
    type: "item",
    textures: ["e"],
    width: 3,
    height: 3,
  },
  magmaKiln: {
    name: "Magma Kiln",
    command: "magmaKiln",
    shortcut: "en",
    phase: "build",
    type: "item",
    textures: ["e"],
    width: 3,
    height: 3,
  },
  glassWindow: {
    name: "Glass Window",
    command: "glassWindow",
    shortcut: "",
    phase: "build",
    type: "item",
    textures: ["y"],
  },
  gemWindow: {
    name: "Gem Window",
    command: "gemWindow",
    shortcut: "",
    phase: "build",
    type: "item",
    textures: ["Y"],
  },
  constructWall: {
    name: "Wall",
    command: "constructWall",
    shortcut: "Cw",
    phase: "build",
    type: "item",
    textures: ["O"],
  },
  constructFloor: {
    name: "Floor",
    command: "constructFloor",
    shortcut: "Cf",
    phase: "build",
    type: "item",
    textures: ["plus"],
  },
  constructRamp: {
    name: "Ramp",
    command: "constructRamp",
    shortcut: "Cr",
    phase: "build",
    type: "item",
    textures: ["rampUp"],
  },
  constructUpStair: {
    name: "Up Stair",
    command: "constructUpStair",
    shortcut: "Cu",
    phase: "build",
    type: "item",
    textures: ["stairsUp"],
  },
  constructDownStair: {
    name: "Down Stair",
    command: "constructDownStair",
    shortcut: "Cj",
    phase: "build",
    type: "item",
    textures: ["stairsDown"],
  },
  constructUpDownStair: {
    name: "Up / Down Stair",
    command: "constructUpDownStair",
    shortcut: "Cx",
    phase: "build",
    type: "item",
    textures: ["X"],
  },
  constructFortification: {
    name: "Fortification",
    command: "constructFortification",
    shortcut: "CF",
    phase: "build",
    type: "item",
    textures: ["smoothWallCross"],
  },
  tradeDepot: {
    name: "Trade Depot",
    command: "tradeDepot",
    shortcut: "D",
    phase: "build",
    type: "item",
    textures: ["D"],
    width: 5,
    height: 5,
  },
  stoneFallTrap: {
    name: "Stone-Fall Trap",
    command: "stoneFallTrap",
    shortcut: "Ts",
    phase: "build",
    type: "item",
    textures: ["caret"],
  },
  weaponTrap: {
    name: "Weapon Trap",
    command: "weaponTrap",
    shortcut: "Tw",
    phase: "build",
    type: "item",
    textures: ["caret"],
  },
  lever: {
    name: "Lever",
    command: "lever",
    shortcut: "Tl",
    phase: "build",
    type: "item",
    textures: ["leverOff"],
  },
  pressurePlate: {
    name: "Pressure Plate",
    command: "pressurePlate",
    shortcut: "Tp",
    phase: "build",
    type: "item",
    textures: ["caret"],
  },
  cageTrap: {
    name: "Cage Trap",
    command: "cageTrap",
    shortcut: "Tc",
    phase: "build",
    type: "item",
    textures: ["caret"],
  },
  uprightSpearSpike: {
    name: "Upright Spear/Spike",
    command: "uprightSpearSpike",
    shortcut: "TS",
    phase: "build",
    type: "item",
    textures: ["riverVertical"],
  },
  screwPump: {
    name: "Screw Pump",
    command: "screwPump",
    shortcut: "Ms",
    phase: "build",
    type: "item",
    textures: ["S"],
  },
  waterWheel: {
    name: "Water Wheel",
    command: "waterWheel",
    shortcut: "Mw",
    phase: "build",
    type: "item",
    textures: ["w"],
  },
  windmill: {
    name: "Windmill",
    command: "windmill",
    shortcut: "Mm",
    phase: "build",
    type: "item",
    textures: ["W"],
  },
  gearAssembly: {
    name: "Gear Assembly",
    command: "gearAssembly",
    shortcut: "Mg",
    phase: "build",
    type: "item",
    textures: ["splat"],
  },
  horizontalAxle: {
    name: "Horizontal Axle",
    command: "horizontalAxle",
    shortcut: "Mh",
    phase: "build",
    type: "item",
    textures: ["riverVertical"],
  },
  verticalAxle: {
    name: "Vertical Axle",
    command: "verticalAxle",
    shortcut: "Mv",
    phase: "build",
    type: "item",
    textures: ["o"],
  },
  support: {
    name: "Support",
    command: "support",
    shortcut: "S",
    phase: "build",
    type: "item",
    textures: ["I"],
  },
  animalTrap: {
    name: "Animal Trap",
    command: "animalTrap",
    shortcut: "m",
    phase: "build",
    type: "item",
    textures: ["animalTrap"],
  },
  restraint: {
    name: "Restraint",
    command: "restraint",
    shortcut: "v",
    phase: "build",
    type: "item",
    textures: ["restraint"],
  },
  cage: {
    name: "Cage",
    command: "cage",
    shortcut: "j",
    phase: "build",
    type: "item",
    textures: ["cage"],
  },
  archeryTarget: {
    name: "Archery Target",
    command: "archeryTarget",
    shortcut: "A",
    phase: "build",
    type: "item",
    textures: ["X"],
  },
  tractionBench: {
    name: "Traction Bench",
    command: "tractionBench",
    shortcut: "R",
    phase: "build",
    type: "item",
    textures: ["T"],
  },
  animalStockpile: {
    name: "Animal Stockpile",
    command: "animalStockpile",
    shortcut: "a",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  foodStockpile: {
    name: "Food Stockpile",
    command: "foodStockpile",
    shortcut: "f",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  furnitureStorageStockpile: {
    name: "Furniture Storage Stockpile",
    command: "furnitureStorageStockpile",
    shortcut: "u",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  graveyardStockpile: {
    name: "Graveyard Stockpile",
    command: "graveyardStockpile",
    shortcut: "y",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  refuseStockpile: {
    name: "Refuse Stockpile",
    command: "refuseStockpile",
    shortcut: "r",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  stoneStockpile: {
    name: "Stone Stockpile",
    command: "stoneStockpile",
    shortcut: "s",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  woodStockpile: {
    name: "Wood Stockpile",
    command: "woodStockpile",
    shortcut: "w",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  gemStockpile: {
    name: "Gem Stockpile",
    command: "gemStockpile",
    shortcut: "e",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  barBlockStockpile: {
    name: "Bar/Block Stockpile",
    command: "barBlockStockpile",
    shortcut: "b",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  clothStockpile: {
    name: "Cloth Stockpile",
    command: "clothStockpile",
    shortcut: "h",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  leatherStockpile: {
    name: "Leather Stockpile",
    command: "leatherStockpile",
    shortcut: "l",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  ammoStockpile: {
    name: "Ammo Stockpile",
    command: "ammoStockpile",
    shortcut: "z",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  coinsStockpile: {
    name: "Coins Stockpile",
    command: "coinsStockpile",
    shortcut: "n",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  finishedGoodsStockpile: {
    name: "Finished Goods Stockpile",
    command: "finishedGoodsStockpile",
    shortcut: "g",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  weaponsStockpile: {
    name: "Weapons Stockpile",
    command: "weaponsStockpile",
    shortcut: "p",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  armorStockpile: {
    name: "Armor Stockpile",
    command: "armorStockpile",
    shortcut: "d",
    phase: "place",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  // quickfort aliases
  seedsStockpile: {
    name: "Seeds Stockpile",
    command: "seedsStockpile",
    shortcut: "seeds",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  noseedsStockpile: {
    name: "No Seeds Stockpile",
    command: "noseedsStockpile",
    shortcut: "noseeds",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  boozeStockpile: {
    name: "Booze Stockpile",
    command: "boozeStockpile",
    shortcut: "booze",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  edibleFoodStockpile: {
    name: "Food Stockpile",
    command: "edibleFoodStockpile",
    shortcut: "food",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  plantsStockpile: {
    name: "Plants Stockpile",
    command: "plantsStockpile",
    shortcut: "plants",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  corpsesStockpile: {
    name: "Corpses Stockpile",
    command: "corpsesStockpile",
    shortcut: "corpses",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  bonesStockpile: {
    name: "Bones Stockpile",
    command: "bonesStockpile",
    shortcut: "bones",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  rawhidesStockpile: {
    name: "Raw Hides Stockpile",
    command: "rawhidesStockpile",
    shortcut: "rawhides",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  tannedhidesStockpile: {
    name: "Tanned Hides Stockpile",
    command: "tannedhidesStockpile",
    shortcut: "tannedhides",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  metalStockpile: {
    name: "Metal Stockpile",
    command: "metalStockpile",
    shortcut: "metal",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  nometalStockpile: {
    name: "No Metal Stockpile",
    command: "nometalStockpile",
    shortcut: "nometal",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  bauxiteStockpile: {
    name: "Bauxite Stockpile",
    command: "bauxiteStockpile",
    shortcut: "bauxite",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  nobauxiteStockpile: {
    name: "No Bauxite Stockpile",
    command: "nobauxiteStockpile",
    shortcut: "nobauxite",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  artifactsStockpile: {
    name: "Artifacts Stockpile",
    command: "artifactsStockpile",
    shortcut: "artifacts",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  noartifactsStockpile: {
    name: "No Artifacts Stockpile",
    command: "noartifactsStockpile",
    shortcut: "noartifacts",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
  junkgoodsStockpile: {
    name: "Junk Goods Stockpile",
    command: "junkgoodsStockpile",
    shortcut: "junkgoods",
    phase: "query",
    type: "item",
    textures: ["stockpileEmpty"],
  },
};
