export const adjustmentMap = {
  makeBedroom: {
    name: "Make Bedroom",
    slug: "makeBedroom",
    shortcut: "r",
    phase: "query",
    type: "resize",
    requires: "bed",
    initialSize: 3,
  },
  makeDiningRoom: {
    name: "Make Dining Room",
    slug: "makeDiningRoom",
    shortcut: "r",
    phase: "query",
    type: "resize",
    requires: "table",
    initialSize: 3,
  },
  seedsStockpile: {
    name: "Seeds Stockpile",
    slug: "seedsStockpile",
    shortcut: "seeds",
    phase: "query",
    type: "select",
    requires: "foodStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  noseedsStockpile: {
    name: "No Seeds Stockpile",
    slug: "noseedsStockpile",
    shortcut: "noseeds",
    phase: "query",
    type: "select",
    requires: "foodStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  boozeStockpile: {
    name: "Booze Stockpile",
    slug: "boozeStockpile",
    shortcut: "booze",
    phase: "query",
    type: "select",
    requires: "foodStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  edibleFoodStockpile: {
    name: "Food Stockpile",
    slug: "edibleFoodStockpile",
    shortcut: "food",
    phase: "query",
    type: "select",
    requires: "foodStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  plantsStockpile: {
    name: "Plants Stockpile",
    slug: "plantsStockpile",
    shortcut: "plants",
    phase: "query",
    type: "select",
    requires: "foodStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  corpsesStockpile: {
    name: "Corpses Stockpile",
    slug: "corpsesStockpile",
    shortcut: "corpses",
    phase: "query",
    type: "select",
    requires: "refuseStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  bonesStockpile: {
    name: "Bones Stockpile",
    slug: "bonesStockpile",
    shortcut: "bones",
    phase: "query",
    type: "select",
    requires: "refuseStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  rawhidesStockpile: {
    name: "Raw Hides Stockpile",
    slug: "rawhidesStockpile",
    shortcut: "rawhides",
    phase: "query",
    type: "select",
    requires: "refuseStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  tannedhidesStockpile: {
    name: "Tanned Hides Stockpile",
    slug: "tannedhidesStockpile",
    shortcut: "tannedhides",
    phase: "query",
    type: "select",
    requires: "refuseStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  metalStockpile: {
    name: "Metal Stockpile",
    slug: "metalStockpile",
    shortcut: "metal",
    phase: "query",
    type: "select",
    requires: "stoneStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  nometalStockpile: {
    name: "No Metal Stockpile",
    slug: "nometalStockpile",
    shortcut: "nometal",
    phase: "query",
    type: "select",
    requires: "stoneStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  bauxiteStockpile: {
    name: "Bauxite Stockpile",
    slug: "bauxiteStockpile",
    shortcut: "bauxite",
    phase: "query",
    type: "select",
    requires: "stoneStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  nobauxiteStockpile: {
    name: "No Bauxite Stockpile",
    slug: "nobauxiteStockpile",
    shortcut: "nobauxite",
    phase: "query",
    type: "select",
    requires: "stoneStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  artifactsStockpile: {
    name: "Artifacts Stockpile",
    slug: "artifactsStockpile",
    shortcut: "artifacts",
    phase: "query",
    type: "select",
    requires: "finishedGoodsStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  noartifactsStockpile: {
    name: "No Artifacts Stockpile",
    slug: "noartifactsStockpile",
    shortcut: "noartifacts",
    phase: "query",
    type: "select",
    requires: "finishedGoodsStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
  junkgoodsStockpile: {
    name: "Junk Goods Stockpile",
    slug: "junkgoodsStockpile",
    shortcut: "junkgoods",
    phase: "query",
    type: "select",
    requires: "finishedGoodsStockpile",
    selectCommand: "stockpile",
    selectName: "Stockpile Type",
  },
} as const;
